### ISSUE TITLE
JSON fixtures

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/varuint-bitcoin#1]
Would you be open to moving the fixtures to `test/fixtures.json` so they can easily be reviewed?
Also, thoughts on adopting some of the vectors from https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/fixtures/bufferutils.json#L1 ?

**Comment by fanatid** [comment]
it would be great!

**Comment by fanatid** [comment]
@dcousens done! https://github.com/bitcoinjs/varuint-bitcoin/commit/990c04df92fd1ec105d94d410a08fe8829e88124

**Comment by dcousens** [comment]
Awesome! :)
