### ISSUE TITLE
Move to bitcoinjs organization?

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/varuint-bitcoin#2]
Up to you @fanatid,  I think it'd be worthwhile.

**Comment by fanatid** [comment]
I haven't rights for transferring to `bitcoinjs`, so I transfer to you

**Comment by dcousens** [comment]
I'll give you rights

**Comment by fanatid** [comment]
done :) I added you and @jprichardson on [npm](https://www.npmjs.com/package/varuint-bitcoin)
