### ISSUE TITLE
Encode should check for the size of the supplied buffer

### ISSUE THREAD

**Issue by axic** [bitcoinjs/varuint-bitcoin#5]
Would it make sense checking the supplied `buffer` if it is big enough?

https://github.com/bitcoinjs/varuint-bitcoin/blob/master/index.js#L9

**Comment by fanatid** [comment]
@axic if buffer length is not enough error will be raised from buffer
for example `writeUInt32LE` -- https://github.com/nodejs/node/blob/d6e56fd843895356769774aebe28b0206ea86d35/lib/buffer.js#L1078

**Comment by axic** [comment]
Fair enough!
