### ISSUE TITLE
Rename to just varuint

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/varuint-bitcoin#7]
Thoughts @fanatid ?

**Comment by fanatid** [comment]
@dcousens why are you already published package with such name? :(
postfix `-bitcoin` was added for easier difference from other varint schemas, like https://github.com/chrisdickinson/varint

**Comment by dcousens** [comment]
@fanatid to try it out,  I can just unpublish?  Only tramples the exact version number, others can re-claim it :+1:

**Comment by dcousens** [comment]
> postfix -bitcoin was added for easier difference from other varint schemas, like https://github.com/chrisdickinson/varint

We don't follow that standard with our other packages though?

**Comment by dcousens** [comment]
Unpublished
